#!/bin/sh
#
# This file is part of MCUSim, an XSPICE library with microcontrollers.
#
# Copyright (C) 2017-2019 MCUSim Developers, see AUTHORS.txt for contributors.
#
# MCUSim is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# MCUSim is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#


# This script patches NGSpice sources to compile MCUSim code model library,
# i.e. mcusim.cm.
echo "Working directory is: `pwd`"

echo "Copying directories..."
for dir in $(find ../patches -type d -name '*'); do
	cp -p -R $dir ./
done

echo "Applying MCUSim patches for NGSpice..."
PATCH=`which patch`
for line in $(find ../patches -name 'ngspice-*.patch*'); do
	echo $line
        $PATCH -p0 -f -u --silent --input=$line
done
